---
spring:
  cloud:
    function:
      definition: stringProducer;stringConsumer
    stream:
      bindings:
        stringProducer-out-0:
          destination: input-topic
        stringConsumer-in-0:
          destination: input-topic
          group: consumer-group
      kafka:
        binder:
          producer-properties:
            "key.serializer": org.apache.kafka.common.serialization.StringSerializer
          consumer-properties:
            "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
            "auto.offset.reset": "earliest"
            "group.instance.id": "1"