---
spring:
  cloud:
    function:
      definition: orderEventProducer;orderProcessor;digitalDeliveryReceiver;physicalDeliveryReceiver
    stream:
      bindings:
        orderEventProducer-out-0:
          destination: order-events-topic
        orderProcessor-in-0:
          destination: order-events-topic
          group: processor-group
        digitalDeliveryReceiver-in-0:
          destination: digital-delivery-topic
          group: digital-delivery-group
        physicalDeliveryReceiver-in-0:
          destination: physical-delivery-topic
          group: physical-delivery-group
      kafka:
        binder:
          producer-properties:
            "key.serializer": org.apache.kafka.common.serialization.StringSerializer
          consumer-properties:
            "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
            "auto.offset.reset": "earliest"
            "group.instance.id": "1"