---
spring:
  cloud:
    function:
      definition: stringFunction
    stream:
      bindings:
        stringConsumer-in-0:
          destination: input-topic
          group: string-group
        stringFunction-in-0:
          destination: input-topic
          group: string-group